### PR TITLE
V0.15.0 update

### PR DESCRIPTION
**Pull request by sigma-andex**
Moving from the working group package set to the official alpha package set.
Upgrading to the latest version 0.15.0-alpha-05

Creating this new PR to not interfere with users of the current es-modules branch.

### CODE REVIEW

**Comment by sigma-andex** [comment]
@fsoikin with the latest version I get the following error:

```console
[1/1 NoInstanceFound] test/Foreign.purs:33:28

  33            readRecord rec = read rec `shouldEqual` Just (Obj.fromHomogeneous rec)
                                 ^^^^^^^^
  
  No type class instance was found for
  
    Elmish.Foreign.CanReceiveFromJavaScript (Object a2)
  
  The following instance partially overlaps the above constraint, which means the rest of its instance chain will not be considered:
  
    Elmish.Foreign.canReceiveFromJavaScriptO
  
  while applying a function read
    of type CanReceiveFromJavaScript t0 => t1 -> Maybe t0
    to argument rec
  while inferring the type of read rec
  in value declaration spec
  
  where a2 is a rigid type variable
          bound at (line 0, column 0 - line 0, column 0)
        t1 is an unknown type
        t0 is an unknown type

           Src   Lib   All
Warnings   1     0     1  
Errors     1     0     1  
[error] Failed to build.
```
I'm pretty sure this is due to this breaking change https://github.com/purescript/purescript/pull/4149
Do you have an idea how to fix this?

**Comment by fsoikin** [comment]
I think you just need to replace `CanReceiveFromJavaScript a` with `CanReceiveFromJavaScript (Object a)` in the signature or `readRecord`

With the new fix the compiler can't reliably derive the latter from the former, because it can't prove that `a` is apart from `Foreign`, but the caller can provide the `Object a` instance, because it knows what `a` is.

**Comment by sigma-andex** [comment]
Great, that did the trick! Thx

**Comment by sigma-andex** [comment]
@fsoikin My guess is that v0.15 will be released within the next few days. I have rebased this PR and the elmish-hooks PR to your latest elmish version. The elmish-hooks PR still has some error, which is similar to the one above, so somewhere a type annotation needs to be added I guess. 
I'm not sure how you would like to go forward with the migration.

**Comment by fsoikin** [comment]
Thank you for all the help.
We are going to merge these PRs and cut new versions just as soon as v0.15 is out. We will also finally add all the latest versions to the package set at that point.

**Comment by sigma-andex** [comment]
Great! Looking forward to that

**Comment by sigma-andex** [comment]
Ok two last minute changes but now it should be ready to go. The packages.dhall will need to be updated once the manually added dependencies are in the package set, but I guess you can take it from there.

**Comment by sigma-andex** [comment]
Good point. Updated it now.

**Review by mcordova47 — APPROVED** [review]
Thanks!

**Comment by mcordova47** [comment]
The build is failing for some reason 🤔  Strangely, `npm run test` passes for me on `12.22` but fails for the version our CI is using (`12.16`).

**Comment by sigma-andex** [comment]
Right, I just updated this to Node.js version 14, which is the new LTS.

**Pull request merged**
